name       : 0ad-data
version    : 0.0.24b
release    : 6
source     :
    - https://releases.wildfiregames.com/0ad-0.0.24b-alpha-unix-data.tar.xz : 41f5868379749aa20b96a8fa2e60dc872ebe22047db061c7cc894462e897a32c
license    :
    - GPL-2.0-or-later
    - CCPL
component  : games
summary    : Cross-platform, 3D and historically-based real-time strategy game (data files)
description: |
    Cross-platform, 3D and historically-based real-time strategy game (data files)
install    : |
    gamedatadir=$installdir/usr/share/0ad/data
    install -d -m 00644 $gamedatadir
    mv binaries/data/* $gamedatadir/
