name       : 0ad-data
version    : 0.0.25a
release    : 7
source     :
    - https://releases.wildfiregames.com/0ad-0.0.25-alpha-unix-data.tar.xz : 97a0e4268b439b5e88d56f66869d702764251a98ef1465af94b57127342a0cb5
license    :
    - GPL-2.0-or-later
    - CCPL
component  : games
summary    : Cross-platform, 3D and historically-based real-time strategy game (data files)
description: |
    Cross-platform, 3D and historically-based real-time strategy game (data files)
install    : |
    gamedatadir=$installdir/usr/share/0ad/data
    install -d -m 00644 $gamedatadir
    mv binaries/data/* $gamedatadir/
